vault-operator/pkg/vault/deploy_vault.go

This PR will replace `TCP` and `UDP` magic string with `v1.ProtocolUDP` and `v1.ProtocolTCP`.

remove magic string about protocol

---

memcached-operator/test/e2e/memcached_test.go

The previous import pointed to the SDK's test libraries, not this project's own libraries.

memcached-operater/test/e2e: fix an import url

---

vault-operator/cmd/vault-operator/main.go

The old main.go file from the vault-operator was outdated and did
not work outside of the default namespace. This update resyncs it
based on the current main.go template, which supports non-default
namespaces.

vault/cmd/.../main.go: update operator main.go

---

memcached-operator/Gopkg.lock
memcached-operator/cmd/memcached-operator/main.go
memcached-operator/test/e2e/memcached_test.go

Golang is pass-by-value, so passing the value of ctx meant that
any finalizer functions added in memcachedScaleTest were not being
run. This commit changes that by using a pointer instead.
This also adds a finalizer function for the example-memcached CR, which is why we need to pass a pointer instead of the value.

memcached/test/e2e: use pointer to ctx, not struct

---

memcached-operator/README.md
memcached-operator/deploy/sa.yaml
memcached-operator/tmp/build/go-test.sh
memcached-operator/tmp/build/test-framework/Dockerfile

See: https://github.com/operator-framework/operator-sdk-samples/pull/38#issuecomment-431734532
This also has a commit to update the kubectl commands in the README

deploy,tmp,README.md: remove old files and update readme

---

memcached-operator/pkg/controller/memcached/memcached_controller.go

This makes the memcached-operator sample use the status updater when updating the status. While the tests did pass, the status blocks weren't being updated since the status is now a subresource. This is not something that gets checked in the tests so it slipped through in the initial `v0.4.0` rebase PR.

memcached/.../memcached_controller: use status update

---

memcached-operator/pkg/controller/memcached/memcached_controller.go
memcached-operator/test/e2e/memcached_test.go
vault-operator/pkg/vault/deploy_etcd.go
vault-operator/pkg/vault/deploy_vault.go
vault-operator/pkg/vault/sync_vault.go
vault-operator/pkg/vault/tls.go
vault-operator/pkg/vault/vault_config.go
vault-operator/pkg/vault/vault_status.go
vault-operator/test/e2e/basic_test.go
vault-operator/test/e2e/e2eutil/spec_util.go
vault-operator/test/e2e/scale_test.go
vault-operator/test/e2e/upgrade_test.go

I originally started looking at this from the perspective of the test
examples, where something didn't look 100% to me, so I figured I'd
open a PR to start a discussion and figure out if my understanding is
correct or not.
Example:
Should the `Kind` in the following snippet not be `MemcachedList`
rather than `Memcached`?
```go
memcachedList := &operator.MemcachedList{
TypeMeta: metav1.TypeMeta{
Kind:       "Memcached",
APIVersion: "cache.example.com/v1alpha1",
},
}
```
I've seen the same thing in other operators, and I'm not sure if it's
the correct way, or if it's just wrong copied from this example.
As I think more about it, all of the correct information seems to be
inferrable from the type (`operator.MemcachedList`), so the `TypeMeta`
never needs to be added manually. Is that correct? …

Don't manually specify TypeMeta field

---

memcached-operator/pkg/controller/memcached/memcached_controller.go
memcached-operator/pkg/controller/memcached/memcached_controller_test.go

https://github.com/operator-framework/operator-sdk/issues/1464
- Add a service object
- Do not Requeue when it is not required. 
- Improve the test
- Make clear for users that are not required Requeue always 
- Make more clear how to CRUD the objects
- Make more clear how to test it since now has 2 objects and we can make show it better
- See here the changes: https://github.com/operator-framework/operator-sdk-samples/pull/67/commits/1dbcc41f4ac1ce75411583c6bb3d06abf4dc8cba
- Execute locally the CI test. 
-  You can use the image: docker.io/cmacedo/mobile-security-service-operator:memcached-operator
- Run :
```
$ oc new-project memcached-operator
$ kubectl apply -f deploy/crds/cache_v1alpha1_memcached_crd.yaml
$ kubectl apply -f deploy/crds/cache_v1alpha1_memcached_cr.yaml
$ kubectl apply …
```

feat(MencacheExample) : Improve example in order to make more clear how it works

---

memcached-operator/test/e2e/memcached_test.go

Use `WaitForOperatorDeployment` instead of `WaitForDeployment` when waiting for `memcached-operator`. This allows the `--up-local` flag to work properly.
Related to the conversation here: https://github.com/operator-framework/operator-sdk/issues/1830#issuecomment-527395768

memcached/test/e2e: use WaitForOperatorDeployment

---

ansible/etcd-operator/ansible/roles/lookup/tasks/main.retry
ansible/etcd-operator/ansible/roles/reconcile/tasks/main.retry

These are created by Ansible when a playbook fails. They should not be
committed to version control.
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

Remove Ansible .retry files

---

memcached-operator/README.md

This PR adds `test-e2e` target in README. It is an important target and should have a place in README.

Update README to add test related target

---

ansible/memcached-operator/.travis.yml

Please see https://github.com/operator-framework/operator-sdk/issues/2023 for more details.

Adjust Travisfile to install required jmespath dependency per operator-sdk #2023.

---

helm/memcached-operator/build/Dockerfile
helm/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
helm/memcached-operator/deploy/role.yaml
helm/memcached-operator/watches.yaml

**Description**
- Upgrade helm based image (Dockerfile)
- Upgrade scaffold files ( roles and crd )
- Upgrade watch since no longer is required to inform the full path. (https://github.com/operator-framework/operator-sdk/pull/2325)
**Local Test**
```
$ kubectl get all -n helm-memcached -o wide
NAME                                      READY   STATUS    RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
pod/example-memcached-0                   1/1     Running   0          38s   172.17.0.8    minikube   <none>           <none>
pod/example-memcached-1                   1/1     Running   0          24s   172.17.0.9    minikube   <none>           <none>
pod/example-memcached-2                   1/1     Running   0          17s   172.17.0.10   minikube   <none> …
```

Helm upgrade for 0.14.1

---

ansible/memcached-operator/watches.yaml

**Motivation**
- Allow users to check that in the 0.15.x they can use relative paths
- Allow we easily test locally it by running `operator-sdk run --local`

update project to use relative paths in the watches

---

helm/memcached-operator/build/Dockerfile
helm/memcached-operator/deploy/operator.yaml
helm/memcached-operator/helm-charts/memcached/README.md
helm/memcached-operator/helm-charts/memcached/values.yaml

**Description**
- Upgrade Helm Sample to use 0.17
**Motivation**
Release of SDK 0.17
**Local Test**
```
$ kubectl get all -n helm-memcached -o wide
NAME                                      READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
pod/example-memcached-0                   1/1     Running   0          27s   172.17.0.6   minikube   <none>           <none>
pod/example-memcached-1                   1/1     Running   0          16s   172.17.0.7   minikube   <none>           <none>
pod/example-memcached-2                   0/1     Running   0          3s    172.17.0.8   minikube   <none>           <none>
pod/memcached-operator-5459696774-pcwjs   1/1     Running   0          33s   172.17.0.4   minikube   <none>           <none>
NAME …
```

Upgrade Helm Sample to use sdk 0.17

---

ansible/memcached-operator/.travis.yml
ansible/memcached-operator/build/Dockerfile
ansible/memcached-operator/molecule/cluster/converge.yml
ansible/memcached-operator/molecule/cluster/molecule.yml
ansible/memcached-operator/molecule/default/converge.yml
ansible/memcached-operator/molecule/default/molecule.yml
ansible/memcached-operator/molecule/default/prepare.yml
ansible/memcached-operator/molecule/test-local/converge.yml
ansible/memcached-operator/molecule/test-local/molecule.yml

**Description**
- Upgrade Ansible Sample to use 0.17
**Motivation**
Release of SDK 0.17
**Local Test**
```
$ kubectl get all -n memcached
NAME                                               READY   STATUS    RESTARTS   AGE
pod/example-memcached-memcached-6456bdd5fc-4xvkz   1/1     Running   0          7s
pod/example-memcached-memcached-6456bdd5fc-7shxl   1/1     Running   0          7s
pod/example-memcached-memcached-6456bdd5fc-cwdm9   1/1     Running   0          7s
pod/memcached-operator-864bbcd-tsc2c               1/1     Running   0          51s
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/memcached-operator-metrics   ClusterIP   10.111.142.126   <none>        8383/TCP,8686/TCP   16s
NAME …
```

Upgrade Ansible Sample to use 0.17

---

helm/memcached-operator/build/Dockerfile
helm/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
helm/memcached-operator/helm-charts/memcached/Chart.yaml
helm/memcached-operator/helm-charts/memcached/templates/statefulset.yaml
helm/memcached-operator/watches.yaml

**Local Test**
```shell
$ kubectl get all -n helm-memcached
NAME                                      READY   STATUS    RESTARTS   AGE
pod/example-memcached-0                   1/1     Running   0          34s
pod/example-memcached-1                   0/1     Running   0          8s
pod/memcached-operator-5459696774-x7l66   1/1     Running   0          56s
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/example-memcached            ClusterIP   None            <none>        11211/TCP           34s
service/memcached-operator-metrics   ClusterIP   10.111.227.89   <none>        8383/TCP,8686/TCP   35s
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/memcached-operator   1/1     1 …
```

upgrade helm sample to use sdk 0.18.1

---

ansible/memcached-operator/build/Dockerfile
ansible/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
ansible/memcached-operator/deploy/operator.yaml
ansible/memcached-operator/molecule/templates/operator.yaml.j2
ansible/memcached-operator/roles/memcached/README.md
ansible/memcached-operator/roles/memcached/defaults/main.yml
ansible/memcached-operator/roles/memcached/handlers/main.yml
ansible/memcached-operator/roles/memcached/meta/main.yml
ansible/memcached-operator/roles/memcached/tasks/main.yml
ansible/memcached-operator/roles/memcached/tests/inventory
ansible/memcached-operator/roles/memcached/tests/test.yml
ansible/memcached-operator/roles/memcached/vars/main.yml

Upgrade the Ansible to use the SDK 0.18
Local test: 
```
$ kubectl get all -n memcached
NAME                                               READY   STATUS    RESTARTS   AGE
pod/example-memcached-memcached-6456bdd5fc-5sff9   1/1     Running   0          44s
pod/example-memcached-memcached-6456bdd5fc-jl8d5   1/1     Running   0          44s
pod/example-memcached-memcached-6456bdd5fc-rf586   1/1     Running   0          44s
pod/memcached-operator-7bb5fb9d9c-cd4qb            1/1     Running   0          55s
NAME                                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/memcached-operator-metrics   ClusterIP   10.110.98.29   <none>        8383/TCP,8686/TCP   50s
NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE …
```

feat: upgrade Ansible sample to use 0.18.1 SDK version

---

helm/memcached-operator/build/Dockerfile
helm/memcached-operator/helm-charts/memcached/README.md

**Description**
- Upgrade Helm Sample to use 0.19.2
**Local Test**
```
$ kubectl get all -n helm-memcached 
NAME                                      READY   STATUS    RESTARTS   AGE
pod/example-memcached-0                   1/1     Running   0          111s
pod/example-memcached-1                   1/1     Running   0          94s
pod/example-memcached-2                   1/1     Running   0          82s
pod/memcached-operator-5459696774-krcgg   1/1     Running   0          2m9s
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/example-memcached            ClusterIP   None             <none>        11211/TCP           111s
service/memcached-operator-metrics   ClusterIP   10.107.150.102   <none>        8383/TCP,8686/TCP   113s …
```

upgrade helm sample 0.19.2

---

helm/README.md

When reading the README in my code editor, syntax highlighting was messed up in the README due to some extra backticks around the example in the 'Troubleshooting' section.﻿

Fix extra backticks that made their way into the Helm sample README
